from flask import Flask, request, jsonify
import smtplib
from flask_cors import CORS
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

app = Flask(__name__)
CORS(app)



# Email configuration
EMAIL_ADDRESS = ''  
EMAIL_PASSWORD = ''   

@app.route('/send-email', methods=['GET'])
@app.route('/send-email', methods=['POST'])

    
    # Your email sending logic here
def send_email():
    try:
        recipient_email = ""  
        subject = "Fall Detected"
        body = "This email is auto-generated by the system. A fall was detected"

        # Create the email
        msg = MIMEMultipart()
        msg['From'] = EMAIL_ADDRESS
        msg['To'] = recipient_email
        msg['Subject'] = subject
        msg.attach(MIMEText(body, 'plain'))

        # Connect to the email server and send the email
        with smtplib.SMTP('smtp.gmail.com', 587) as server:
            server.starttls()
            server.login(EMAIL_ADDRESS, EMAIL_PASSWORD)
            server.sendmail(EMAIL_ADDRESS, recipient_email, msg.as_string())

            # Return a successful JSON response
            return jsonify({'message': 'Email sent successfully!'}), 200

    except Exception as e:
        # Return an error response if email sending fails
        return jsonify({'error': str(e)}), 500
if __name__ == '__main__':
    app.run(debug=True)
